In [1]:
import os
import pandas as pd


# 1. Mendapatkan path ke folder Desktop secara otomatis
folder_path = r'C:\protofolio\ecommerce_analytic\data mentah'

# 3. Membaca file menggunakan pandas
df_campaigns = pd.read_csv(os.path.join(folder_path, 'campaigns.csv')).copy()
df_campaigns.head()

,campaign_id,channel,objective,start_date,end_date,target_segment,expected_uplift
0,1,Paid Search,Cross-sell,2021-10-25,2021-11-26,Deal Seekers,0.022
1,2,Email,Retention,2021-10-24,2021-12-24,Deal Seekers,0.116
2,3,Email,Reactivation,2023-10-08,2023-11-30,Churn Risk,0.100
3,4,Display,Reactivation,2022-07-25,2022-10-07,Deal Seekers,0.111
4,5,Social,Acquisition,2022-07-09,2022-09-29,New Customers,0.144

In [2]:
df_campaigns.isnull().sum()

campaign_id        0
channel            0
objective          0
start_date         0
end_date           0
target_segment     0
expected_uplift    0
dtype: int64

In [3]:
df_campaigns['channel'].unique()
df_campaigns['objective'].unique()
df_campaigns['target_segment'].unique()

<StringArray>
['Deal Seekers', 'Churn Risk', 'New Customers', 'High Value', 'All']
Length: 5, dtype: str

In [4]:
df_campaigns['start_date']=pd.to_datetime(df_campaigns['start_date'])
df_campaigns['end_date']=pd.to_datetime(df_campaigns['end_date'])

df_campaigns['duration_days'] =df_campaigns['end_date'] - df_campaigns['start_date']

display(df_campaigns[['campaign_id','start_date','end_date','duration_days']].head())

   campaign_id start_date   end_date duration_days
0            1 2021-10-25 2021-11-26       32 days
1            2 2021-10-24 2021-12-24       61 days
2            3 2023-10-08 2023-11-30       53 days
3            4 2022-07-25 2022-10-07       74 days
4            5 2022-07-09 2022-09-29       82 days

In [5]:
display(df_campaigns.head())

,campaign_id,channel,objective,start_date,end_date,target_segment,expected_uplift,duration_days
0,1,Paid Search,Cross-sell,2021-10-25,2021-11-26,Deal Seekers,0.022,32 days
1,2,Email,Retention,2021-10-24,2021-12-24,Deal Seekers,0.116,61 days
2,3,Email,Reactivation,2023-10-08,2023-11-30,Churn Risk,0.100,53 days
3,4,Display,Reactivation,2022-07-25,2022-10-07,Deal Seekers,0.111,74 days
4,5,Social,Acquisition,2022-07-09,2022-09-29,New Customers,0.144,82 days

In [6]:
#  durasi menjadi angka (jumlah hari)
df_campaigns['duration_days_int'] = df_campaigns['duration_days'].dt.days

# Mengelompokkan berdasarkan channel untuk melihat performa rata-rata
channel_performance = df_campaigns.groupby('channel')[['expected_uplift', 'duration_days_int']].mean()


display(channel_performance.round(2))

# Mengurutkan berdasarkan expected_uplift dari tertinggi (descending)
sorted_performance = channel_performance.sort_values(by='expected_uplift', ascending=False)

display(sorted_performance.round(2))

             expected_uplift  duration_days_int
channel
Affiliate               0.10              56.73
Display                 0.09              48.78
Email                   0.07              49.18
Paid Search             0.09              49.36
Social                  0.07              50.25

             expected_uplift  duration_days_int
channel
Affiliate               0.10              56.73
Paid Search             0.09              49.36
Display                 0.09              48.78
Email                   0.07              49.18
Social                  0.07              50.25

In [7]:
display(df_campaigns.head())

,campaign_id,channel,objective,start_date,end_date,target_segment,expected_uplift,duration_days,duration_days_int
0,1,Paid Search,Cross-sell,2021-10-25,2021-11-26,Deal Seekers,0.022,32 days,32
1,2,Email,Retention,2021-10-24,2021-12-24,Deal Seekers,0.116,61 days,61
2,3,Email,Reactivation,2023-10-08,2023-11-30,Churn Risk,0.100,53 days,53
3,4,Display,Reactivation,2022-07-25,2022-10-07,Deal Seekers,0.111,74 days,74
4,5,Social,Acquisition,2022-07-09,2022-09-29,New Customers,0.144,82 days,82

In [8]:
# save cleand data
df_campaigns.to_csv(r'C:\protofolio\ecommerce_analytic\data bersih\dim_campaigns_clean.csv', index=False)
print("File sudah tersimpan!")

File sudah tersimpan!