In [1]:
import os
import pandas as pd


# 1. Mendapatkan path ke folder Desktop secara otomatis
folder_path = r'C:\protofolio\ecommerce_analytic\data bersih'

# 3. Membaca file menggunakan pandas
df_master = pd.read_csv(os.path.join(folder_path, 'master_clean.csv')).copy()

df_transactions = pd.read_csv(os.path.join(folder_path, 'transactions_clean.csv')).copy()



df_master.head()

,event_id,timestamp,customer_id,session_id,event_type,product_id,device_type,traffic_source,campaign_id,page_category,...,loyalty_tier,acquisition_channel,channel,objective,start_date,end_date,target_segment,expected_uplift,duration_days,duration_days_int
0,1,2021-01-14 13:35:43,43812,535101,view,1004.0,desktop,Email,43,PLP,...,Bronze,Email,Paid Search,Cross-sell,2023-03-12,2023-04-18,Deal Seekers,0.078,37 days,37.0
1,2,2021-12-03 21:36:50,71340,96426,add_to_cart,986.0,desktop,Email,10,PDP,...,Bronze,Referral,Email,Cross-sell,2022-09-01,2022-10-22,Churn Risk,0.034,51 days,51.0
2,3,2021-12-27 08:25:15,59540,220126,purchase,1630.0,mobile,Organic,0,PDP,...,Silver,Organic,Organic/Direct,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2022-01-22 15:06:54,3601,484555,add_to_cart,1532.0,desktop,Paid Search,30,Checkout,...,Bronze,Email,Social,Acquisition,2023-11-04,2024-01-06,Deal Seekers,0.052,63 days,63.0
4,5,2021-05-10 12:03:09,92735,60646,bounce,-1.0,desktop,Email,26,PLP,...,Bronze,Email,Email,Reactivation,2023-08-13,2023-11-01,Deal Seekers,0.037,80 days,80.0

In [2]:
# Hitung rata-rata/perfotma konversi per channel
df_konversi= df_master.groupby('channel')['event_type'].value_counts(normalize=True)*100
print(df_konversi)

channel         event_type
Affiliate       view           50.280584
                click          18.198630
                add_to_cart    13.472557
                bounce          9.099542
                purchase        8.948686
Display         view           50.350616
                click          18.464830
                add_to_cart    13.683709
                bounce          9.188623
                purchase        8.312222
Email           view           50.687174
                click          18.490264
                add_to_cart    13.921231
                bounce          9.290368
                purchase        7.610964
Organic/Direct  view           53.843785
                click          19.526599
                add_to_cart    14.718906
                bounce          9.815736
                purchase        2.094974
Paid Search     view           50.334963
                click          18.309622
                add_to_cart    13.680220
                bounce          9.100425
                purchase        8.574770
Social          view           51.020114
                click          18.441005
                add_to_cart    13.866157
                bounce          9.215490
                purchase        7.457234
Name: proportion, dtype: float64

In [3]:
df_master.head()

,event_id,timestamp,customer_id,session_id,event_type,product_id,device_type,traffic_source,campaign_id,page_category,...,loyalty_tier,acquisition_channel,channel,objective,start_date,end_date,target_segment,expected_uplift,duration_days,duration_days_int
0,1,2021-01-14 13:35:43,43812,535101,view,1004.0,desktop,Email,43,PLP,...,Bronze,Email,Paid Search,Cross-sell,2023-03-12,2023-04-18,Deal Seekers,0.078,37 days,37.0
1,2,2021-12-03 21:36:50,71340,96426,add_to_cart,986.0,desktop,Email,10,PDP,...,Bronze,Referral,Email,Cross-sell,2022-09-01,2022-10-22,Churn Risk,0.034,51 days,51.0
2,3,2021-12-27 08:25:15,59540,220126,purchase,1630.0,mobile,Organic,0,PDP,...,Silver,Organic,Organic/Direct,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2022-01-22 15:06:54,3601,484555,add_to_cart,1532.0,desktop,Paid Search,30,Checkout,...,Bronze,Email,Social,Acquisition,2023-11-04,2024-01-06,Deal Seekers,0.052,63 days,63.0
4,5,2021-05-10 12:03:09,92735,60646,bounce,-1.0,desktop,Email,26,PLP,...,Bronze,Email,Email,Reactivation,2023-08-13,2023-11-01,Deal Seekers,0.037,80 days,80.0

In [4]:
df_master['event_type'].unique()

<StringArray>
['view', 'add_to_cart', 'purchase', 'bounce', 'click']
Length: 5, dtype: str

In [5]:
#transaksi
df_transaksi = df_master[df_master['event_type'] == 'purchase']

display(df_transaksi.head())

,event_id,timestamp,customer_id,session_id,event_type,product_id,device_type,traffic_source,campaign_id,page_category,...,loyalty_tier,acquisition_channel,channel,objective,start_date,end_date,target_segment,expected_uplift,duration_days,duration_days_int
2,3,2021-12-27 08:25:15,59540,220126,purchase,1630.0,mobile,Organic,0,PDP,...,Silver,Organic,Organic/Direct,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,2023-06-06 21:14:26,54871,179212,purchase,1901.0,mobile,Paid Search,21,PLP,...,Bronze,Paid Search,Email,Acquisition,2023-02-21,2023-03-27,Churn Risk,0.090,34 days,34.0
21,22,2023-08-31 05:29:54,51818,496917,purchase,1884.0,desktop,Social,37,PLP,...,Platinum,Organic,Paid Search,Cross-sell,2022-10-20,2022-12-01,Deal Seekers,0.096,42 days,42.0
31,32,2022-06-26 20:33:46,18164,352305,purchase,1114.0,desktop,Email,13,PLP,...,Bronze,Organic,Display,Reactivation,2022-03-19,2022-06-09,Churn Risk,0.063,82 days,82.0
57,58,2023-07-26 18:12:35,86915,33967,purchase,408.0,mobile,Email,4,PLP,...,Bronze,Email,Display,Reactivation,2022-07-25,2022-10-07,Deal Seekers,0.111,74 days,74.0

In [6]:
#perilaku user
df_user_activity = df_master.groupby('customer_id')['event_type'].count()
display(df_user_activity.head())

customer_id
1    18
2    19
3    14
4    23
5    11
Name: event_type, dtype: int64

In [7]:
# Melihat detail aktivitas per customer (berapa view, berapa purchase, dll)
df_detail_user = df_master.groupby(['customer_id', 'event_type']).size().unstack(fill_value=0)
display(df_detail_user.head())

event_type   add_to_cart  bounce  click  purchase  view
customer_id
1                      1       0      7         0    10
2                      3       2      3         1    10
3                      4       1      0         0     9
4                      1       3      7         0    12
5                      1       2      1         0     7

In [8]:
#cek user di df_transactions 
df_transaksi_user_cek = df_transactions[df_transactions['customer_id'] == 59540]

display(df_transaksi_user_cek.head())

,transaction_id,timestamp,customer_id,product_id,quantity,discount_applied,gross_revenue,campaign_id,refund_flag,net_revenue,transaction_date
0,1,2021-12-27 08:25:15,59540,1630.0,3,0.0,43.74,0,0,43.74,2021-12-27

In [9]:
##cek user di df_master

df_master_user_cek = df_master[df_master['customer_id'] == 59540]

display(df_master_user_cek.head())

,event_id,timestamp,customer_id,session_id,event_type,product_id,device_type,traffic_source,campaign_id,page_category,...,loyalty_tier,acquisition_channel,channel,objective,start_date,end_date,target_segment,expected_uplift,duration_days,duration_days_int
2,3,2021-12-27 08:25:15,59540,220126,purchase,1630.0,mobile,Organic,0,PDP,...,Silver,Organic,Organic/Direct,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11830,11831,2022-11-02 05:02:50,59540,307353,view,351.0,desktop,Social,12,PDP,...,Silver,Organic,Email,Acquisition,2021-01-20,2021-02-21,Churn Risk,0.032,32 days,32.0
23924,23925,2022-07-09 12:51:57,59540,606676,view,618.0,mobile,Organic,0,Home,...,Silver,Organic,Organic/Direct,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80700,80701,2023-10-01 14:00:40,59540,546063,view,1949.0,mobile,Email,26,Checkout,...,Silver,Organic,Email,Reactivation,2023-08-13,2023-11-01,Deal Seekers,0.037,80 days,80.0
147267,147268,2021-09-16 08:00:11,59540,133038,add_to_cart,776.0,desktop,Paid Search,30,PDP,...,Silver,Organic,Social,Acquisition,2023-11-04,2024-01-06,Deal Seekers,0.052,63 days,63.0