In [1]:
import os
import pandas as pd


# 1. Mendapatkan path ke folder Desktop secara otomatis
folder_path = r'C:\protofolio\ecommerce_analytic\data mentah'

# 3. Membaca file menggunakan pandas
df_events = pd.read_csv(os.path.join(folder_path, 'events.csv')).copy()
df_events.head()

,event_id,timestamp,customer_id,session_id,event_type,product_id,device_type,traffic_source,campaign_id,page_category,session_duration_sec,experiment_group
0,1,2021-01-14 13:35:43,43812,535101,view,1004.0,desktop,Email,43,PLP,115.1,Control
1,2,2021-12-03 21:36:50,71340,96426,add_to_cart,986.0,desktop,Email,10,PDP,32.4,Variant_A
2,3,2021-12-27 08:25:15,59540,220126,purchase,1630.0,mobile,Organic,0,PDP,190.7,Variant_A
3,4,2022-01-22 15:06:54,3601,484555,add_to_cart,1532.0,desktop,Paid Search,30,Checkout,134.8,Variant_B
4,5,2021-05-10 12:03:09,92735,60646,bounce,NaN,desktop,Email,26,PLP,53.1,Variant_A

In [2]:
df_events.isnull().sum()
#print(df_events.isnull().sum().mean())

event_id                     0
timestamp                    0
customer_id                  0
session_id                   0
event_type                   0
product_id              200371
device_type              40300
traffic_source               0
campaign_id                  0
page_category                0
session_duration_sec         0
experiment_group             0
dtype: int64

In [3]:
#fill product id yang kosong -1 sebagai penanda
df_events['product_id']=df_events['product_id'].fillna(-1)
df_events['product_id'].value_counts()

product_id
-1.0       200371
 1023.0      1008
 1872.0       999
 1984.0       996
 3.0          992
            ...
 915.0        816
 1656.0       816
 1310.0       813
 45.0         813
 585.0        799
Name: count, Length: 2001, dtype: int64

In [4]:
df_events['device_type'].unique()
#fill device null as unknown
df_events['device_type']=df_events['device_type'].fillna('unknown')
df_events['device_type'].value_counts()

device_type
mobile     1176146
desktop     685433
tablet       98121
unknown      40300
Name: count, dtype: int64

In [5]:
#change data type ['event_type','device_type','traffic_source','page_category'] as category menghemat memory yg di simpan di memory jadi kode mis 1,1,3
col_to_cat=['event_type','device_type','traffic_source','page_category']
for col in col_to_cat:
    df_events[col] = df_events[col].astype('category')

display(df_events.head())   
df_events.info()

,event_id,timestamp,customer_id,session_id,event_type,product_id,device_type,traffic_source,campaign_id,page_category,session_duration_sec,experiment_group
0,1,2021-01-14 13:35:43,43812,535101,view,1004.0,desktop,Email,43,PLP,115.1,Control
1,2,2021-12-03 21:36:50,71340,96426,add_to_cart,986.0,desktop,Email,10,PDP,32.4,Variant_A
2,3,2021-12-27 08:25:15,59540,220126,purchase,1630.0,mobile,Organic,0,PDP,190.7,Variant_A
3,4,2022-01-22 15:06:54,3601,484555,add_to_cart,1532.0,desktop,Paid Search,30,Checkout,134.8,Variant_B
4,5,2021-05-10 12:03:09,92735,60646,bounce,-1.0,desktop,Email,26,PLP,53.1,Variant_A

<class 'pandas.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 12 columns):
 #   Column                Dtype
---  ------                -----
 0   event_id              int64
 1   timestamp             str
 2   customer_id           int64
 3   session_id            int64
 4   event_type            category
 5   product_id            float64
 6   device_type           category
 7   traffic_source        category
 8   campaign_id           int64
 9   page_category         category
 10  session_duration_sec  float64
 11  experiment_group      str
dtypes: category(4), float64(2), int64(4), str(2)
memory usage: 129.7 MB

In [6]:
#change timestamp to date for time serie analys an merger table 
df_events['timestamp']=pd.to_datetime(df_events['timestamp'])

df_events['created_at']=df_events['timestamp'].dt.date

display(df_events[['timestamp','customer_id','created_at']].head())

            timestamp  customer_id  created_at
0 2021-01-14 13:35:43        43812  2021-01-14
1 2021-12-03 21:36:50        71340  2021-12-03
2 2021-12-27 08:25:15        59540  2021-12-27
3 2022-01-22 15:06:54         3601  2022-01-22
4 2021-05-10 12:03:09        92735  2021-05-10

In [7]:
df_events.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 13 columns):
 #   Column                Dtype
---  ------                -----
 0   event_id              int64
 1   timestamp             datetime64[us]
 2   customer_id           int64
 3   session_id            int64
 4   event_type            category
 5   product_id            float64
 6   device_type           category
 7   traffic_source        category
 8   campaign_id           int64
 9   page_category         category
 10  session_duration_sec  float64
 11  experiment_group      str
 12  created_at            object
dtypes: category(4), datetime64[us](1), float64(2), int64(4), object(1), str(1)
memory usage: 145.0+ MB

In [9]:
# save clean data
df_events.to_csv(r'C:\protofolio\ecommerce_analytic\data bersih\events_clean.csv', index=False)
print("File sudah tersimpan!")

File sudah tersimpan!