In [1]:
import os
import pandas as pd


# 1. Mendapatkan path ke folder Desktop secara otomatis
folder_path = r'C:\protofolio\ecommerce_analytic\data mentah'

# 3. Membaca file menggunakan pandas
df_products = pd.read_csv(os.path.join(folder_path, 'products.csv')).copy()
df_products.head()

   product_id     category     brand  base_price launch_date  is_premium
0           1      Grocery  Brand_58       14.19  2021-08-02           0
1           2      Fashion   Brand_1       25.80  2021-09-14           0
2           3  Electronics  Brand_70      165.46  2021-01-18           1
3           4      Fashion  Brand_56       75.45  2023-03-03           1
4           5       Sports   Brand_1       72.50  2022-04-19           1

In [2]:
#ck duplicate id df_products['product_id']

duplicated_id=df_products[df_products.duplicated('product_id',keep=False)]
print(f"total duplikat {len(duplicated_id)}")

total duplikat 0

In [3]:
df_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   product_id   2000 non-null   int64
 1   category     2000 non-null   str
 2   brand        2000 non-null   str
 3   base_price   2000 non-null   float64
 4   launch_date  2000 non-null   str
 5   is_premium   2000 non-null   int64
dtypes: float64(1), int64(2), str(3)
memory usage: 93.9 KB

In [4]:
#change laundh_date to date tie
df_products['launch_date']=pd.to_datetime(df_products['launch_date'])
df_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   product_id   2000 non-null   int64
 1   category     2000 non-null   str
 2   brand        2000 non-null   str
 3   base_price   2000 non-null   float64
 4   launch_date  2000 non-null   datetime64[us]
 5   is_premium   2000 non-null   int64
dtypes: datetime64[us](1), float64(1), int64(2), str(2)
memory usage: 93.9 KB

In [5]:
df_products['category'].value_counts()
#df_products['brand'].value_counts()

#change category and brand data type as category
col_to_cat= df_products[['category','brand']].astype('category')
for col in col_to_cat:
    df_products[col]= df_products[col].astype('category')

df_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   product_id   2000 non-null   int64
 1   category     2000 non-null   category
 2   brand        2000 non-null   category
 3   base_price   2000 non-null   float64
 4   launch_date  2000 non-null   datetime64[us]
 5   is_premium   2000 non-null   int64
dtypes: category(2), datetime64[us](1), float64(1), int64(2)
memory usage: 67.4 KB

In [6]:
print(df_products['category'].unique())

['Grocery', 'Fashion', 'Electronics', 'Sports', 'Beauty', 'Home']
Categories (6, str): ['Beauty', 'Electronics', 'Fashion', 'Grocery', 'Home', 'Sports']

In [7]:
df_products.head()

   product_id     category     brand  base_price launch_date  is_premium
0           1      Grocery  Brand_58       14.19  2021-08-02           0
1           2      Fashion   Brand_1       25.80  2021-09-14           0
2           3  Electronics  Brand_70      165.46  2021-01-18           1
3           4      Fashion  Brand_56       75.45  2023-03-03           1
4           5       Sports   Brand_1       72.50  2022-04-19           1

In [8]:
# save clean data
df_products.to_csv(r'C:\protofolio\ecommerce_analytic\data bersih\products_clean.csv', index=False)
print("File sudah tersimpan!")

File sudah tersimpan!